# Generated by Django 4.0.5 on 2022-06-06 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_owner', models.CharField(max_length=255)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Extracts',
            fields=[
                ('extract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extract_date', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(related_name='extracts', to='contas.accounts')),
            ],
        ),
    ]
