# Generated by Django 4.0.5 on 2022-06-06 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_owner', models.CharField(max_length=255)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('extract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extract_date', models.DateTimeField(auto_now=True)),
                ('former_account_balance', models.FloatField()),
                ('current_account_balance', models.FloatField()),
                ('extract_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_value', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('transaction_description', models.CharField(max_length=255)),
                ('transaction_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.accounts')),
                ('transaction_extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contas.extract')),
            ],
        ),
    ]
