# Generated by Django 4.0.5 on 2022-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_owner',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
